# Generated by Django 5.0 on 2023-12-05 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=300)),
    # operations = [
    #     migrations.AddField(
    #         model_name='logmessage',
    #         name='log_date',
    #         field=models.DateTimeField(...),
    #     ),
            ],
        ),
    ]
