# Generated by Django 5.0 on 2023-12-06 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logmessage',
            name='log_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date logged'),
        ),
    ]
