# Generated by Django 4.2.5 on 2023-12-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_logmessage_log_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="logmessage",
            name="class_field",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="logmessage",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="logmessage",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
